# autogenerated lists
-include sources.mk
-include includes.mk

# ===== Project =====
NAME        = voxels
BUILD_DIR   = build
OBJ_DIR     = $(BUILD_DIR)/obj
BIN         = $(BUILD_DIR)/$(NAME)

INCLUDES_PATH = ./inc

# map sources -> objects in build/
OBJS        = $(patsubst %.cpp,$(OBJ_DIR)/%.o,$(SOURCES))
DEPS        = $(OBJS:.o=.d)

# ===== Colors =====
BLACK        = \033[0;30m
RED          = \033[0;31m
GREEN        = \033[0;32m
ORANGE       = \033[0;33m
BLUE         = \033[0;34m
PURPLE       = \033[0;35m
CYAN         = \033[0;36m
LIGHT_GRAY   = \033[0;37m
DARK_GRAY    = \033[1;30m
LIGHT_RED    = \033[1;31m
LIGHT_GREEN  = \033[1;32m
YELLOW       = \033[1;33m
LIGHT_BLUE   = \033[1;34m
LIGHT_PURPLE = \033[1;35m
LIGHT_CYAN   = \033[1;36m
WHITE        = \033[1;37m
RESET        = \033[0m

# ===== Toolchain =====
CXX         = g++
CXXFLAGS    = -std=c++20 -Wall -Wextra -Werror -O3 -flto -march=native -ffast-math \
              -I$(INCLUDES_PATH) -MMD -MP
LDFLAGS     = -flto
LDLIBS      =  # tbd

RM          = rm -rf

# ===== Targets =====
all: sources.mk includes.mk $(BIN)

# link final executable into build/
$(BIN): $(OBJS)
	@mkdir -p $(dir $@)
	@$(CXX) $(OBJS) $(LDFLAGS) $(LDLIBS) -o $@
	@printf "\033[2K\r$(BLUE)$(NAME): $(GREEN)Linked → $(BIN) [√]$(RESET)\n"

# compile .cpp -> build/obj/... .o
$(OBJ_DIR)/%.o: %.cpp $(INCLUDES)
	@mkdir -p $(dir $@)
	@$(CXX) $(CXXFLAGS) -c $< -o $@
	@printf "\033[2K\r$(BLUE)$(NAME): $(PURPLE)$<$(RESET)"

# clean only objects & dep files
clean:
	@$(RM) $(OBJ_DIR)
	@printf "$(BLUE)$(NAME): $(YELLOW)Cleaned object files$(RESET)\n"

# full clean: blow away the entire build/ directory
fclean:
	@$(RM) $(BUILD_DIR)
	@printf "$(BLUE)$(NAME): $(YELLOW)Removed $(BUILD_DIR)/$(RESET)\n"

re: fclean all

# helper to run the program
run: $(BIN)
	@./$(BIN)

# generate/refresh sources/includes lists
sources.mk includes.mk:
	@find src -name '*.cpp' | sed 's/^/SOURCES += /' > sources.mk
	@find inc -name '*.hpp'   | sed 's/^/INCLUDES += /' > includes.mk
	@printf "$(BLUE)$(NAME): $(GREEN)Refreshed sources/includes lists$(RESET)\n"

.PHONY: all clean fclean re init run

# Include auto-generated dependency files
-include $(DEPS)
